### ISSUE TITLE
Raw strings do not work

### ISSUE THREAD

**Issue by stanford-scs** [ludwigpacifici/modern-cpp-font-lock#14]
The documentation suggests that raw strings should be properly highlighted, but this does not seem to work.  To reproduce this, I started from a completely clean .emacs file and then ran:

``` .el
(package-initialize)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
(package-refresh-contents)
(package-install 'modern-cpp-font-lock)
(modern-c++-font-lock-global-mode t)
```

I then opened a new C++ file, verified that `modern-c++-string-literal` was indeed `t`, but unfortunately still do not get proper highlighting:

![mfl](https://user-images.githubusercontent.com/4564109/27520424-49cd27dc-59c0-11e7-9249-f19805c7dc3b.png)

**Comment by stanford-scs** [comment]
This was solved by upgrading to cc-mode 5.33.  But ideally that should be documented somewhere...

**Comment by ludwigpacifici** [comment]
Hello @stanford-scs 

I am aware of the conflict between `c++-mode` and `modern-cpp-font-lock` - `c++-mode` uses the [Emacs syntax table](https://www.emacswiki.org/emacs/EmacsSyntaxTable) to highlight strings. Then `modern-cpp-font-lock` cannot override the highlight of string via `font-lock-string-face` because the syntax table is setup by the major mode and `modern-cpp-font-lock` is only a minor mode.

I'll update the README.md to give more information.

**Comment by ludwigpacifici** [comment]
Added in the Wiki: https://github.com/ludwigpacifici/modern-cpp-font-lock/wiki#known-issues
