### ISSUE TITLE
Does this package support C++20 features?

### ISSUE THREAD

**Issue by wouterbeek** [ludwigpacifici/modern-cpp-font-lock#33]
(I am not a native English speaker, so my problem may be due to lack of knowledge on my part.)

When I read the primary description of what this package is about:

> Syntax highlighting support for "Modern C++" - until C++20 and Technical Specification.

I am left with the question whether or not this package supports C++20 language features.  The semantics of the English word "until" seems to be *exclusive* and not *inclusive* (according to [Dictionary.com](https://www.dictionary.com/browse/until?s=t)).

This would mean that this package does *not* support C++20 features.  Is that indeed the intended reading of this package description?

**Comment by ludwigpacifici** [comment]
This package supports few C++20 keywords.

Last time I was working on this package (2019), C++20 was not released, but few keywords were already available, such as `co_await` or `const_eval`. So, this package supports few C++20 keywords. You can look at the last commits or the Elisp code to know what is supported.

If some are missing, you can open a PR for it. However, it is better to work these issues with the maintainer of [CC Mode](http://cc-mode.sourceforge.net/) because the fix will be available in vanilla Emacs. You can drop an email at bug-cc-mode@gnu.org.

**Comment by wouterbeek** [comment]
Thanks for the clarification.
