### ISSUE TITLE
ObjC support

### ISSUE THREAD

**Issue by Pitometsu** [ludwigpacifici/modern-cpp-font-lock#8]
Any plans for `ObjC(++)` as well (because based on same `libClang`?

**Comment by ludwigpacifici** [comment]
This package does not depend on `libClang` or any other library. I want it too work without dependencies since it is not guaranteed such library will be installed on your computer. Plus this package aims C++ and not Objective-C. So I am have no plans for Objective-C.

You could easily do an equivalent project to support it. Let me know if you need some help.

**Comment by Pitometsu** [comment]
Thank you.
